# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_auto_20180317_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='name',
        ),
    ]
