# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_auto_20180319_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighborhood_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Neighborhood'),
        ),
    ]
